[build]
  command = "npm run build"
  publish = "dist"

# أي request يبدأ بـ /api/ يروح للـ API الحقيقي
[[redirects]]
  from = "/api/*"
  to = "https://deebai.runasp.net/api/:splat"
  status = 200
  force = true

# أي route تاني يروح لل index.html (React SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
